### ISSUE TITLE
Front end rework

### ISSUE THREAD

**Issue by HonakerM** [RPIForge/channels#8]
The front end needs to be reworked with the following requirements:

1. Popup from the bottom of the page accessible on all pages
2. Nice looking Chat bubbles like most chat sites
3. Input buttons placed dynamically
4. Formalize wording of the site

**Comment by bnidevs** [comment]
👍

**Comment by bnidevs** [comment]
need write access pls

**Comment by HonakerM** [comment]
Sorry! All web-mainters now have write access. Please still branch and oped a pull request

**Comment by bnidevs** [comment]
chat bubbles done c39da27c167f5a39f9b1d5ce2fa63946a9fa73b8

**Comment by bnidevs** [comment]
input buttons done f1a621afc4c04e3e54d12cdc17f85026f52bd416

**Comment by HonakerM** [comment]
Fixed in commit b48d4da
